# Form implementation generated from reading ui file 'tray_setting.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TraySetting(object):
    def setupUi(self, TraySetting):
        TraySetting.setObjectName("TraySetting")
        TraySetting.resize(684, 410)
        self.label = QtWidgets.QLabel(TraySetting)
        self.label.setGeometry(QtCore.QRect(30, 40, 91, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.textEdit_sqlWhere = QtWidgets.QTextEdit(TraySetting)
        self.textEdit_sqlWhere.setGeometry(QtCore.QRect(120, 40, 501, 181))
        self.textEdit_sqlWhere.setObjectName("textEdit_sqlWhere")
        self.label_2 = QtWidgets.QLabel(TraySetting)
        self.label_2.setGeometry(QtCore.QRect(20, 258, 91, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_min = QtWidgets.QLineEdit(TraySetting)
        self.lineEdit_min.setGeometry(QtCore.QRect(120, 258, 81, 20))
        self.lineEdit_min.setObjectName("lineEdit_min")
        self.label_3 = QtWidgets.QLabel(TraySetting)
        self.label_3.setGeometry(QtCore.QRect(210, 258, 91, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_save = QtWidgets.QPushButton(TraySetting)
        self.pushButton_save.setGeometry(QtCore.QRect(220, 350, 75, 23))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_cancel = QtWidgets.QPushButton(TraySetting)
        self.pushButton_cancel.setGeometry(QtCore.QRect(380, 350, 75, 23))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_4 = QtWidgets.QLabel(TraySetting)
        self.label_4.setGeometry(QtCore.QRect(20, 300, 91, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_order_offset = QtWidgets.QLineEdit(TraySetting)
        self.lineEdit_order_offset.setGeometry(QtCore.QRect(120, 300, 81, 20))
        self.lineEdit_order_offset.setObjectName("lineEdit_order_offset")

        self.retranslateUi(TraySetting)
        QtCore.QMetaObject.connectSlotsByName(TraySetting)

    def retranslateUi(self, TraySetting):
        _translate = QtCore.QCoreApplication.translate
        TraySetting.setWindowTitle(_translate("TraySetting", "壁纸切换设置"))
        self.label.setText(_translate("TraySetting", "筛选语句："))
        self.label_2.setText(_translate("TraySetting", "间隔时间："))
        self.label_3.setText(_translate("TraySetting", "分钟"))
        self.pushButton_save.setText(_translate("TraySetting", "保存"))
        self.pushButton_cancel.setText(_translate("TraySetting", "取消"))
        self.label_4.setText(_translate("TraySetting", "起始偏移："))
